-- Sample data for Oracle database demo

-- Insert departments
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (10, 'Administration', 200, 1700);
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (20, 'Marketing', 201, 1800);
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (30, 'Purchasing', 114, 1700);
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (40, 'Human Resources', 203, 2400);
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (50, 'Shipping', 121, 1500);
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (60, 'IT', 103, 1400);

-- Insert employees
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (100, 'Steven', 'King', 'SKING', '515.123.4567', TO_DATE('17-JUN-2003', 'DD-MON-YYYY'), 'AD_PRES', 24000, NULL, NULL, 90);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (101, 'Neena', 'Kochhar', 'NKOCHHAR', '515.123.4568', TO_DATE('21-SEP-2005', 'DD-MON-YYYY'), 'AD_VP', 17000, NULL, 100, 90);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (102, 'Lex', 'De Haan', 'LDEHAAN', '515.123.4569', TO_DATE('13-JAN-2001', 'DD-MON-YYYY'), 'AD_VP', 17000, NULL, 100, 90);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (103, 'Alexander', 'Hunold', 'AHUNOLD', '590.423.4567', TO_DATE('03-JAN-2006', 'DD-MON-YYYY'), 'IT_PROG', 9000, NULL, 102, 60);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (104, 'Bruce', 'Ernst', 'BERNST', '590.423.4568', TO_DATE('21-MAY-2007', 'DD-MON-YYYY'), 'IT_PROG', 6000, NULL, 103, 60);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (107, 'Diana', 'Lorentz', 'DLORENTZ', '590.423.5567', TO_DATE('07-FEB-2008', 'DD-MON-YYYY'), 'IT_PROG', 4200, NULL, 103, 60);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (124, 'Kevin', 'Mourgos', 'KMOURGOS', '650.123.5234', TO_DATE('16-NOV-2007', 'DD-MON-YYYY'), 'ST_MAN', 5800, NULL, 100, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (141, 'Trenna', 'Rajs', 'TRAJS', '650.121.8009', TO_DATE('17-OCT-2003', 'DD-MON-YYYY'), 'ST_CLERK', 3500, NULL, 124, 50);

-- Example of using Oracle MERGE statement (upsert)
MERGE INTO DEPARTMENTS d
USING (SELECT 70 AS dept_id, 'Public Relations' AS dept_name, 204 AS mgr_id, 1700 AS loc_id FROM dual) src
ON (d.DEPARTMENT_ID = src.dept_id)
WHEN MATCHED THEN
    UPDATE SET d.DEPARTMENT_NAME = src.dept_name, d.MANAGER_ID = src.mgr_id, d.LOCATION_ID = src.loc_id
WHEN NOT MATCHED THEN
    INSERT (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
    VALUES (src.dept_id, src.dept_name, src.mgr_id, src.loc_id);

-- Example of Oracle's CONNECT BY for hierarchical queries
-- This creates a log of the sample data load with timestamps
CREATE TABLE DATA_LOAD_LOG (
    LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LOG_MESSAGE VARCHAR2(200),
    LOG_TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP,
    PARENT_LOG_ID NUMBER
);

-- Log hierarchy example
INSERT INTO DATA_LOAD_LOG (LOG_MESSAGE, PARENT_LOG_ID) VALUES ('Started data load process', NULL);
INSERT INTO DATA_LOAD_LOG (LOG_MESSAGE, PARENT_LOG_ID) VALUES ('Loaded department data', 1);
INSERT INTO DATA_LOAD_LOG (LOG_MESSAGE, PARENT_LOG_ID) VALUES ('Loaded employee data', 1);
INSERT INTO DATA_LOAD_LOG (LOG_MESSAGE, PARENT_LOG_ID) VALUES ('Loaded IT department employees', 3);
INSERT INTO DATA_LOAD_LOG (LOG_MESSAGE, PARENT_LOG_ID) VALUES ('Loaded HR department employees', 3);
INSERT INTO DATA_LOAD_LOG (LOG_MESSAGE, PARENT_LOG_ID) VALUES ('Data load completed', 1);

-- Create database link example (would require appropriate privileges)
-- CREATE DATABASE LINK remote_db
--   CONNECT TO remote_user IDENTIFIED BY remote_password
--   USING 'remote_tns_entry';
