logs-directory: "test-files/unprocessed"
processed-logs-directory: "test-files/processed"
logging:
  level:
    root: INFO
    com:
      azure:
        spring: DEBUG
        messaging:
          eventhubs: WARN
        core:
          amqp: WARN
    org:
      springframework:
        integration: WARN
spring:
  cloud:
    azure:
      eventhubs:
        namespace: ${EVENT_HUBS_NAMESPACE}
        event-hub-name: ${EVENT_HUB_NAME}
