# debug: true
spring:
  application:
    name: sample
  cloud:
    azure:
      eventhubs:
        namespace: eventhubnamespaceone
        processor:
          checkpoint-store:
            container-name: containerone
            account-name:  accountone
    function:
      definition: consume;supply
    stream:
      bindings:
        consume-in-0:
          destination: eventhubone
          group: $Default
        supply-out-0:
          destination: eventhubone # same as the above destination
      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
      default:
        producer:
          errorChannelEnabled: true
      poller:
        initial-delay: 0
        fixed-delay: 1000